// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package storage

import (
	"github.com/crazyfrankie/cloud/internal/storage/service"
	"github.com/minio/minio-go/v7"
)

// Injectors from wire.go:

func InitStorageModule(minio2 *minio.Client) *Module {
	storageService := service.NewStorageService(minio2)
	module := &Module{
		Service: storageService,
	}
	return module
}

// wire.go:

type Service = service.StorageService

type Module struct {
	Service *Service
}
