// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package file

import (
	"github.com/crazyfrankie/cloud/internal/file/dao"
	"github.com/crazyfrankie/cloud/internal/file/handler"
	"github.com/crazyfrankie/cloud/internal/file/service"
	"github.com/crazyfrankie/cloud/internal/storage"
	"github.com/minio/minio-go/v7"
	"github.com/redis/go-redis/v9"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitFileModule(db *gorm.DB, st *storage.Module, rdb redis.Cmdable, minio2 *minio.Client) *Module {
	fileDao := dao.NewFileDao(db)
	storageService := st.Service
	fileService := service.NewFileService(fileDao, storageService)
	uploadService := service.NewUploadService(fileDao, fileService, storageService)
	downloadService := service.NewDownloadService(fileDao, storageService, minio2)
	fileHandler := handler.NewFileHandler(uploadService, fileService, downloadService)
	module := &Module{
		Handler: fileHandler,
	}
	return module
}

// wire.go:

type Handler = handler.FileHandler

type Module struct {
	Handler *Handler
}
