// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package file

import (
	"github.com/crazyfrankie/cloud/internal/file/dao"
	"github.com/crazyfrankie/cloud/internal/file/handler"
	"github.com/crazyfrankie/cloud/internal/file/service"
	"github.com/crazyfrankie/cloud/internal/storage"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitFileModule(db *gorm.DB, st *storage.Module) *Module {
	uploadDao := dao.NewUploadDao(db)
	storageService := st.Service
	uploadService := service.NewUploadService(uploadDao, storageService)
	v := handler.NewFileHandler(uploadService)
	module := &Module{
		Handler: v,
	}
	return module
}

// wire.go:

type Handler = handler.FileHandler

type Module struct {
	Handler *Handler
}
