// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"fmt"
	"github.com/crazyfrankie/cloud/internal/auth"
	"github.com/crazyfrankie/cloud/internal/file"
	dao2 "github.com/crazyfrankie/cloud/internal/file/dao"
	"github.com/crazyfrankie/cloud/internal/storage"
	"github.com/crazyfrankie/cloud/internal/user"
	"github.com/crazyfrankie/cloud/internal/user/dao"
	"github.com/crazyfrankie/cloud/pkg/conf"
	"github.com/crazyfrankie/cloud/pkg/middlewares"
	"github.com/crazyfrankie/snow-flake"
	"github.com/gin-gonic/gin"
	"github.com/minio/minio-go/v7"
	"github.com/minio/minio-go/v7/pkg/credentials"
	"github.com/redis/go-redis/v9"
	"gorm.io/driver/mysql"
	"gorm.io/gorm"
	"gorm.io/gorm/schema"
	"os"
)

// Injectors from wire.go:

func InitEngine() *gin.Engine {
	db := InitDB()
	client := InitMinIO()
	node := InitSnowflake()
	module := user.InitUserModule(db, client, node)
	cmdable := InitRedis()
	authModule := auth.InitAuthModule(module, cmdable)
	v := authModule.Token
	v2 := InitMws(v)
	v3 := module.Handler
	v4 := authModule.Handler
	storageModule := storage.InitStorageModule(client)
	v5 := storageModule.Handler
	fileModule := file.InitFileModule(db, storageModule)
	v6 := fileModule.Handler
	engine := InitWeb(v2, v3, v4, v5, v6)
	return engine
}

// wire.go:

func InitDB() *gorm.DB {
	dsn := fmt.Sprintf(conf.GetConf().MySQL.DSN, os.Getenv("MYSQL_USER"), os.Getenv("MYSQL_PASSWORD"), os.Getenv("MYSQL_HOST"), os.Getenv("MYSQL_PORT"), os.Getenv("MYSQL_DB"))

	db, err := gorm.Open(mysql.Open(dsn), &gorm.Config{
		NamingStrategy: schema.NamingStrategy{SingularTable: true},
	})
	if err != nil {
		panic(err)
	}

	db.AutoMigrate(&dao.User{}, &dao2.File{}, &dao2.Folder{})

	return db
}

func InitMinIO() *minio.Client {
	client, err := minio.New(conf.GetConf().MinIO.Endpoint, &minio.Options{
		Creds: credentials.NewStaticV4(conf.GetConf().MinIO.AccessKey, conf.GetConf().MinIO.SecretKey, ""),
	})
	if err != nil {
		panic(err)
	}

	return client
}

func InitRedis() redis.Cmdable {
	client := redis.NewClient(&redis.Options{
		Addr: conf.GetConf().Redis.Addr,
	})

	return client
}

func InitSnowflake() *snowflake.Node {
	node, err := snowflake.NewNode(1)
	if err != nil {
		panic(err)
	}

	return node
}

func InitWeb(mws []gin.HandlerFunc, user2 *user.Handler, auth2 *auth.Handler, storage2 *storage.Handler, file2 *file.Handler) *gin.Engine {
	srv := gin.Default()

	srv.Use(func(c *gin.Context) {
		c.Header("Access-Control-Allow-Origin", "*")
		c.Header("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS")
		c.Header("Access-Control-Allow-Headers", "Origin, Content-Type, Accept, Authorization")

		if c.Request.Method == "OPTIONS" {
			c.AbortWithStatus(204)
			return
		}

		c.Next()
	})

	srv.Use(mws...)

	srv.Static("/web", "./web")
	srv.GET("/", func(c *gin.Context) {
		c.Redirect(302, "/web/")
	})
	user2.
		RegisterRoute(srv)
	auth2.
		RegisterRoute(srv)
	storage2.
		RegisterRoute(srv)
	file2.
		RegisterRoute(srv)

	return srv
}

func InitMws(t *auth.TokenService) []gin.HandlerFunc {
	return []gin.HandlerFunc{middlewares.NewAuthnHandler(t).
		IgnorePath("/user/register").
		IgnorePath("/auth/login").
		IgnorePath("/web/").
		IgnorePath("/web/style.css").
		IgnorePath("/web/app.js").
		IgnorePath("/").Auth(),
	}
}
