// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package auth

import (
	"github.com/crazyfrankie/cloud/internal/auth/handler"
	"github.com/crazyfrankie/cloud/internal/auth/service"
	"github.com/crazyfrankie/cloud/internal/user"
	"github.com/redis/go-redis/v9"
)

// Injectors from wire.go:

func InitAuthModule(u *user.Module, cmd redis.Cmdable) *Module {
	userService := u.Service
	tokenService := service.NewTokenService(cmd)
	authService := service.NewAuthService(userService, tokenService)
	v := handler.NewAuthHandler(authService)
	module := &Module{
		Handler: v,
		Token:   tokenService,
	}
	return module
}

// wire.go:

type Handler = handler.AuthHandler

type TokenService = service.TokenService

type Module struct {
	Handler *Handler
	Token   *TokenService
}
