// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

import (
	"github.com/crazyfrankie/cloud/internal/user/dao"
	"github.com/crazyfrankie/cloud/internal/user/handler"
	"github.com/crazyfrankie/cloud/internal/user/service"
	"github.com/crazyfrankie/snow-flake"
	"github.com/minio/minio-go/v7"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitUserModule(db *gorm.DB, minio2 *minio.Client, snow *snowflake.Node) *Module {
	userDao := dao.NewUserDao(db)
	userService := service.NewUserService(userDao, snow, minio2)
	v := handler.NewUserHandler(userService)
	module := &Module{
		Handler: v,
		Service: userService,
	}
	return module
}

// wire.go:

type Handler = handler.UserHandler

type Service = service.UserService

type Module struct {
	Handler *Handler
	Service *Service
}
